elasticsearch:
  build: ./docker
  dockerfile: Dockerfile-elasticsearch
  container_name: qori_qollqe_elasticsearch
  volumes:
    - ./docker/.volumes/data:/usr/share/elasticsearch/data

kibana:
  build: ./docker
  dockerfile: Dockerfile-kibana
  container_name: qori_qollqe_kibana
  ports:
    - 5601:5601
  links:
    - elasticsearch
  environment:
    - VIRTUAL_HOST=qoriqollqe.localhost
